class GlobalCost:
    LUA_LOCALIZATION_HEADER = """---create lua by localization generator\n 
 ---module:%s\n 
 ---time:%s\n\n
 ---@class const_localization_%s\n
  const_localization_%s={\n"""

    XML_HEADER_CONST = """--- this file is generated by program!
--- don't change it manually.
--- source file: %s
--- created at: %s

local _localization_config={
"""
    XML_END_CONST = """ };
return _localization_config;"""
